//
//  StyleKitName.h
//  paintCodeTutorial
//
//  Created by guibin on 15/12/30.
//  Copyright (c) 2015 J1. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface StyleKitName : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* canvas1Targets;

// Colors
+ (UIColor*)color;

// Drawing Methods
+ (void)drawCanvas1;
+ (void)drawCanvas2;

// Generated Images
+ (UIImage*)imageOfCanvas1;

@end
